version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  tests:
    jobs:
      - ui-tests

jobs:
  ui-tests:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: choco install winappdriver
      - run: choco install maven
      - run: mvn test