version: 2.1

orbs:
  allure: ayte/allure@0.1.3
  win: circleci/windows@2.4.0

workflows:
  tests:
    jobs:
      - ui-tests

jobs:
  ui-tests:
    executor:
      name: win/gpu-nvidia
      shell: powershell.exe
    steps:
      - run: Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm get.scoop.sh | iex
      - run: scoop install allure
      #- allure/install
      - checkout
      - run: choco install winappdriver
      - run: choco install maven
      #- run: Remove-item alias:curl
      - run: mvn test
      - allure/report