version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  tests:
    jobs:
      - ui-tests

jobs:
  ui-tests:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: choco install winappdriver
      - run: choco install maven
      - run: choco install oldcalc
      - run: cd C:\ProgramData\chocolatey\lib\oldcalc\tools ; ls
      - run: explorer shell:AppsFolder\Old Calculator for Windows 10.exe
      - run: get-appxpackage -allusers | Select Name, PackageFullName
      - run: mvn test