version: 2.1

workflows:
  tests:
    jobs:
      - ui-tests

jobs:
  ui-tests:
    docker:
      - image: mcr.microsoft.com/windows:ltsc2019
    steps:
      - checkout
      - run: choco install winappdriver
      - run: choco install maven
      - run: choco install oldcalc
      - run: cd C:\ProgramData\chocolatey\lib\oldcalc\tools ; ls
      - run: explorer shell:AppsFolder\Old Calculator for Windows 10.exe
      - run: get-appxpackage -allusers | Select Name, PackageFullName
      - run: mvn test